include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    prefer_interpolation_to_compose_strings: ignore
    prefer_final_fields: ignore
    constant_identifier_names: ignore
    non_constant_identifier_names: ignore
